#!/usr/bin/env python

# ------------------------------
# License

# Copyright 2024 Aldrin Montana
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# ------------------------------
# Overview
"""
Write a query plan in substrait using ibis.
"""


# ------------------------------
# Dependencies

# >> Standard modules
import os
import sys

from pathlib import Path

# >> Third-party
import ibis

from ibis_substrait.compiler.core import SubstraitCompiler
from ibis_substrait.compiler.core import stp as substrait # substrait.plan_pb2 module


# >> Internal
from mohair.util import ArgparseBuilder


# ------------------------------
# Parse CLI arguments first
if __name__ == '__main__':
    parsed_args, extra_args = (
        ArgparseBuilder.with_description('A sandbox for writing simple substrait plans')
                       .add_output_file_arg(
                            help_str='Path to write resulting substrait plan message'
                           ,default_fpath=os.path.join(
                                'resources', 'test-sandbox.substrait'
                            )
                        )
                       .parse_args()
    )


# ------------------------------
# Support functions

# >> Functions for handling outputs
def WriteSubstraitToFile(msg_fpath: Path, substrait_msg: substrait.Plan) -> str:
    """ Writes a substrait `Plan` message to file at path :msg_fpath:. """

    with msg_fpath.open('wb') as file_handle:
        file_handle.write(substrait_msg.SerializeToString())

    return str(msg_fpath)


# ------------------------------
# Main logic

if __name__ == '__main__':
    # Validate args
    output_fpath = Path(parsed_args.output_file)
    if output_fpath.is_file():
        sys.exit(f'Output file already exists: "{output_fpath}"')

    test_table = ibis.table(
         {
              'first' : 'string'
             ,'second': 'int32'
             ,'third' : 'float'
         }
        ,name='test'
    )

    simple_query = test_table.select(test_table)

    substrait_compiler = SubstraitCompiler()
    proto_msg = substrait_compiler.compile(simple_query)

    WriteSubstraitToFile(output_fpath, proto_msg)

