#!/usr/bin/env python

# ------------------------------
# License

# Copyright 2022 Aldrin Montana
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# ------------------------------
# Dependencies

# >> Standard libs
from pathlib import Path

# >> Internal libs
from mohair.services import DatabaseService


# ------------------------------
# Constants

SERVER_LOC  = 'grpc://0.0.0.0:9999'
DB_FILEPATH = Path('resources') / 'data'


# ------------------------------
# Main Logic

if __name__ == '__main__':
    db_cse = DatabaseService(
         service_location=SERVER_LOC
        ,db_fpath=DB_FILEPATH
    )

    db_cse.serve()
