#!/usr/bin/env python

# ------------------------------
# License

# Copyright 2024 Aldrin Montana
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# ------------------------------
# Overview
"""
Write a query plan in substrait using ibis.
"""


# ------------------------------
# Dependencies

# >> Standard modules
import os
import sys

from pathlib import Path

# >> Third-party
import pyarrow
import ibis

from ibis import udf
from ibis_substrait.compiler.core import SubstraitCompiler
from ibis_substrait.compiler.core import stp as substrait # substrait.plan_pb2 module


# >> Internal
from mohair.util            import ArgparseBuilder
from mohair.query.extension import SkyPartitionTable, SkySliceTable
from mohair.query.types     import ( SkyDomain
                                    ,SkyPartition
                                    ,SkyPartitionMeta
                                    ,SkyPartitionSlice)

# >> Functions
from mohair.util import TableFromBinary, SchemaFromBinary

# >> The workloads we support
from workloads.statistics import BaseSummaryStats


# ------------------------------
# Module variables
SAMPLE_FPATH  = Path('resources') / 'sample-data.tsv'
SAMPLE_SCHEMA = pyarrow.schema([
     pyarrow.field('gene_id'   , pyarrow.string())
    ,pyarrow.field('cell_id'   , pyarrow.string())
    ,pyarrow.field('expression', pyarrow.float32())
])


# ------------------------------
# Parse CLI arguments first
if __name__ == '__main__':
    parsed_args, extra_args = (
        ArgparseBuilder.with_description('Write a substrait plan for a sample query')
                       .add_skytether_domain_arg(required=True)
                       .add_skytether_partition_arg(required=True)
                       .add_workload_arg(required=True)
                       .add_skytether_onlyschema_arg(required=False)
                       .add_input_dir_arg(
                            required=True
                           ,help_str='Path to directory containing source domain'
                        )
                       .add_output_file_arg(
                            help_str='Path to write resulting substrait plan message'
                           ,default_fpath=os.path.join(
                                'resources', 'average-expression.substrait'
                            )
                        )
                       .parse_args()
    )


# ------------------------------
# Support functions

# >> Functions for handling inputs
def DomainForSource(data_srcdir: str, data_dkey: str, data_pkeys: list[str]) -> SkyDomain:
    """ Convenience function to parse source data into a skytether domain. """

    print(f'Creating domain {data_dkey} with partitions: {data_pkeys}')
    domain = SkyDomain.WithName(data_dkey).WithPartitions(data_pkeys)
    print(domain.partitions)

    # Populate schemas and optionally data
    for pname, partition in domain.partitions.items():
        partition_fpath = Path(data_srcdir) / data_dkey / pname

        with open(partition_fpath, 'rb') as partition_handle:
            if parsed_args.schema_only:
                partition.SetSchema(SchemaFromBinary(partition_handle.read()))

            else:
                partition_data = TableFromBinary(partition_handle.read())

                partition.SetSchema(partition_data.schema)
                partition.SetPartitionData(partition_data)

    return domain

# >> Functions for handling outputs
def WriteSubstraitToFile(msg_fpath: Path, substrait_msg: substrait.Plan) -> str:
    """ Writes a substrait `Plan` message to file at path :msg_fpath:. """

    with msg_fpath.open('wb') as file_handle:
        file_handle.write(substrait_msg.SerializeToString())

    return str(msg_fpath)

# >> Functions for generating query plans
def ConstructWorkload(workload_name, sky_domain):

    if workload_name == 'SummaryStats':
        print(sky_domain.partitions.values())
        src_partitions = iter(sky_domain.partitions.values())

        src_partition = next(src_partitions)
        slice_rel     = SkySliceTable.ForPartition(src_partition).to_expr()
        query         = BaseSummaryStats.Accumulate(slice_rel)

        for src_partition in src_partitions:
            slice_rel  = SkySliceTable.ForPartition(src_partition).to_expr()
            stat_query = BaseSummaryStats.Accumulate(slice_rel)
            query      = BaseSummaryStats.Combine(query, stat_query)

        return BaseSummaryStats.Complete(query).unbind()

    sys.exit(f'Unexpected workload name: {workload_name}')
    return None



# ------------------------------
# Main logic

if __name__ == '__main__':
    # Validate args
    substrait_fpath = Path(parsed_args.output_file)
    if substrait_fpath.is_file():
        sys.exit(f'Output file already exists: "{substrait_fpath}"')

    # Construct a skytether domain from the source data
    source_domain = DomainForSource(
         parsed_args.input_dir
        ,parsed_args.domain_key
        ,parsed_args.partition_keys
    )

    # Construct a query from the skytether domain
    workload_query = ConstructWorkload(parsed_args.workload_name, source_domain)

    print(workload_query)

    substrait_compiler = SubstraitCompiler()
    proto_msg = substrait_compiler.compile(workload_query)

    WriteSubstraitToFile(substrait_fpath, proto_msg)

