# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: skyproto/substrait/capabilities.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'skyproto/substrait/capabilities.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%skyproto/substrait/capabilities.proto\x12\x12skyproto.substrait\"\xf5\x02\n\x0c\x43\x61pabilities\x12-\n\x12substrait_versions\x18\x01 \x03(\tR\x11substraitVersions\x12?\n\x1c\x61\x64vanced_extension_type_urls\x18\x02 \x03(\tR\x19\x61\x64vancedExtensionTypeUrls\x12]\n\x11simple_extensions\x18\x03 \x03(\x0b\x32\x30.skyproto.substrait.Capabilities.SimpleExtensionR\x10simpleExtensions\x1a\x95\x01\n\x0fSimpleExtension\x12\x10\n\x03uri\x18\x01 \x01(\tR\x03uri\x12#\n\rfunction_keys\x18\x02 \x03(\tR\x0c\x66unctionKeys\x12\x1b\n\ttype_keys\x18\x03 \x03(\tR\x08typeKeys\x12.\n\x13type_variation_keys\x18\x04 \x03(\tR\x11typeVariationKeysB\x94\x01\n\x16\x63om.skyproto.substraitB\x11\x43\x61pabilitiesProtoP\x01\xa2\x02\x03SSX\xaa\x02\x12Skyproto.Substrait\xca\x02\x12Skyproto\\Substrait\xe2\x02\x1eSkyproto\\Substrait\\GPBMetadata\xea\x02\x13Skyproto::Substraitb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'skyproto.substrait.capabilities_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.skyproto.substraitB\021CapabilitiesProtoP\001\242\002\003SSX\252\002\022Skyproto.Substrait\312\002\022Skyproto\\Substrait\342\002\036Skyproto\\Substrait\\GPBMetadata\352\002\023Skyproto::Substrait'
  _globals['_CAPABILITIES']._serialized_start=62
  _globals['_CAPABILITIES']._serialized_end=435
  _globals['_CAPABILITIES_SIMPLEEXTENSION']._serialized_start=286
  _globals['_CAPABILITIES_SIMPLEEXTENSION']._serialized_end=435
# @@protoc_insertion_point(module_scope)
