# ------------------------------
# Headers and Sources

# >> Headers
libskytether_headers += files(
   'apidep_standard.hpp'
  ,'apidep_arrow.hpp'
  ,'apidep_mohair.hpp'
  ,'engines.hpp'
)


# >> Sources
libskytether_sources += files(
   'engines.cpp'
)


# >> From subdirectories
subdir('engines' / 'duckdb')
subdir('engines' / 'acero')
