[tool.poetry]
name = "mohair"
version = "0.1.0"
description = "query processing for decomposable queries"
authors = ["Aldrin M <octalene.dev@pm.me>"]
license = "Apache License 2.0"
packages = [
     { include = "mohair",   from = "src/python" }
    ,{ include = "skyproto", from = "src/python" }
]

[tool.poetry.dependencies]
python = "^3.12"
numpy = "^2.2.0"
Cython = "^3.0.8"
wheel = "^0.42.0"
click = "^8.1.7"
datafusion = "^35.0.0"
pkgconfig = "^1.5.5"
pyarrow-hotfix = "^0.6"
protobuf = "==5.29.3"
substrait = "^0.23.0"
#ibis-substrait = "==4.0.0"
pyarrow = "^19.0.0"
ibis-skytether = "^0.1.0"
matplotlib = "^3.10.1"
pandas = "^2.2.3"
rich = "^14.0.0"

[tool.poetry.scripts]
mohair = "mohair.cli:cli"

[build-system]
requires = [
   "poetry-core>=1.0.0"
  ,"cython>=0.29"
  ,"setuptools"
  ,"wheel"
  ,"pkgconfig>=1.5.5"
]
build-backend = "poetry.core.masonry.api"
