[tool.poetry]
name = "mohair"
version = "0.1.0"
description = "computational data management system"
authors = ["Aldrin M <octalene.dev@pm.me>"]
license = "Apache License 2.0"

[tool.poetry.dependencies]
python = "^3.10"
numpy = "^1.23.1"
Cython = "^0.29.30"
wheel = "^0.37.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
