# ------------------------------
# Overview


# ------------------------------
# Dependencies


# ------------------------------
# Headers and Sources

# >> Headers
libskytether_headers += files(
   'apidep_substrait.hpp'
  ,'operators.hpp'
  ,'plans.hpp'
)

# >> Sources
libskytether_sources += files(
   'operators.cpp'
  ,'plans.cpp'
)
