// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: substrait/extended_expression.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_substrait_2fextended_5fexpression_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_substrait_2fextended_5fexpression_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4024000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4024002 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "algebra.pb.h"
#include "extensions/extensions.pb.h"
#include "plan.pb.h"
#include "type.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_substrait_2fextended_5fexpression_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_substrait_2fextended_5fexpression_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_substrait_2fextended_5fexpression_2eproto;
namespace substrait {
class ExpressionReference;
struct ExpressionReferenceDefaultTypeInternal;
extern ExpressionReferenceDefaultTypeInternal _ExpressionReference_default_instance_;
class ExtendedExpression;
struct ExtendedExpressionDefaultTypeInternal;
extern ExtendedExpressionDefaultTypeInternal _ExtendedExpression_default_instance_;
}  // namespace substrait
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace substrait {

// ===================================================================


// -------------------------------------------------------------------

class ExpressionReference final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:substrait.ExpressionReference) */ {
 public:
  inline ExpressionReference() : ExpressionReference(nullptr) {}
  ~ExpressionReference() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR ExpressionReference(::google::protobuf::internal::ConstantInitialized);

  ExpressionReference(const ExpressionReference& from);
  ExpressionReference(ExpressionReference&& from) noexcept
    : ExpressionReference() {
    *this = ::std::move(from);
  }

  inline ExpressionReference& operator=(const ExpressionReference& from) {
    CopyFrom(from);
    return *this;
  }
  inline ExpressionReference& operator=(ExpressionReference&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ExpressionReference& default_instance() {
    return *internal_default_instance();
  }
  enum ExprTypeCase {
    kExpression = 1,
    kMeasure = 2,
    EXPR_TYPE_NOT_SET = 0,
  };

  static inline const ExpressionReference* internal_default_instance() {
    return reinterpret_cast<const ExpressionReference*>(
               &_ExpressionReference_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ExpressionReference& a, ExpressionReference& b) {
    a.Swap(&b);
  }
  inline void Swap(ExpressionReference* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ExpressionReference* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ExpressionReference* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ExpressionReference>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ExpressionReference& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const ExpressionReference& from) {
    ExpressionReference::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ExpressionReference* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "substrait.ExpressionReference";
  }
  protected:
  explicit ExpressionReference(::google::protobuf::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kOutputNamesFieldNumber = 3,
    kExpressionFieldNumber = 1,
    kMeasureFieldNumber = 2,
  };
  // repeated string output_names = 3 [json_name = "outputNames"];
  int output_names_size() const;
  private:
  int _internal_output_names_size() const;

  public:
  void clear_output_names() ;
  const std::string& output_names(int index) const;
  std::string* mutable_output_names(int index);
  void set_output_names(int index, const std::string& value);
  void set_output_names(int index, std::string&& value);
  void set_output_names(int index, const char* value);
  void set_output_names(int index, const char* value, std::size_t size);
  void set_output_names(int index, absl::string_view value);
  std::string* add_output_names();
  void add_output_names(const std::string& value);
  void add_output_names(std::string&& value);
  void add_output_names(const char* value);
  void add_output_names(const char* value, std::size_t size);
  void add_output_names(absl::string_view value);
  const ::google::protobuf::RepeatedPtrField<std::string>& output_names() const;
  ::google::protobuf::RepeatedPtrField<std::string>* mutable_output_names();

  private:
  const ::google::protobuf::RepeatedPtrField<std::string>& _internal_output_names() const;
  ::google::protobuf::RepeatedPtrField<std::string>* _internal_mutable_output_names();

  public:
  // .substrait.Expression expression = 1 [json_name = "expression"];
  bool has_expression() const;
  private:
  bool _internal_has_expression() const;

  public:
  void clear_expression() ;
  const ::substrait::Expression& expression() const;
  PROTOBUF_NODISCARD ::substrait::Expression* release_expression();
  ::substrait::Expression* mutable_expression();
  void set_allocated_expression(::substrait::Expression* value);
  void unsafe_arena_set_allocated_expression(::substrait::Expression* value);
  ::substrait::Expression* unsafe_arena_release_expression();

  private:
  const ::substrait::Expression& _internal_expression() const;
  ::substrait::Expression* _internal_mutable_expression();

  public:
  // .substrait.AggregateFunction measure = 2 [json_name = "measure"];
  bool has_measure() const;
  private:
  bool _internal_has_measure() const;

  public:
  void clear_measure() ;
  const ::substrait::AggregateFunction& measure() const;
  PROTOBUF_NODISCARD ::substrait::AggregateFunction* release_measure();
  ::substrait::AggregateFunction* mutable_measure();
  void set_allocated_measure(::substrait::AggregateFunction* value);
  void unsafe_arena_set_allocated_measure(::substrait::AggregateFunction* value);
  ::substrait::AggregateFunction* unsafe_arena_release_measure();

  private:
  const ::substrait::AggregateFunction& _internal_measure() const;
  ::substrait::AggregateFunction* _internal_mutable_measure();

  public:
  void clear_expr_type();
  ExprTypeCase expr_type_case() const;
  // @@protoc_insertion_point(class_scope:substrait.ExpressionReference)
 private:
  class _Internal;
  void set_has_expression();
  void set_has_measure();

  inline bool has_expr_type() const;
  inline void clear_has_expr_type();

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 3, 2, 50, 2> _table_;
  template <typename T> friend class ::google::protobuf::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::google::protobuf::RepeatedPtrField<std::string> output_names_;
    union ExprTypeUnion {
      constexpr ExprTypeUnion() : _constinit_{} {}
        ::google::protobuf::internal::ConstantInitialized _constinit_;
      ::substrait::Expression* expression_;
      ::substrait::AggregateFunction* measure_;
    } expr_type_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint32_t _oneof_case_[1];

    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_substrait_2fextended_5fexpression_2eproto;
};// -------------------------------------------------------------------

class ExtendedExpression final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:substrait.ExtendedExpression) */ {
 public:
  inline ExtendedExpression() : ExtendedExpression(nullptr) {}
  ~ExtendedExpression() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR ExtendedExpression(::google::protobuf::internal::ConstantInitialized);

  ExtendedExpression(const ExtendedExpression& from);
  ExtendedExpression(ExtendedExpression&& from) noexcept
    : ExtendedExpression() {
    *this = ::std::move(from);
  }

  inline ExtendedExpression& operator=(const ExtendedExpression& from) {
    CopyFrom(from);
    return *this;
  }
  inline ExtendedExpression& operator=(ExtendedExpression&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ExtendedExpression& default_instance() {
    return *internal_default_instance();
  }
  static inline const ExtendedExpression* internal_default_instance() {
    return reinterpret_cast<const ExtendedExpression*>(
               &_ExtendedExpression_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ExtendedExpression& a, ExtendedExpression& b) {
    a.Swap(&b);
  }
  inline void Swap(ExtendedExpression* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ExtendedExpression* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ExtendedExpression* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ExtendedExpression>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ExtendedExpression& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const ExtendedExpression& from) {
    ExtendedExpression::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ExtendedExpression* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "substrait.ExtendedExpression";
  }
  protected:
  explicit ExtendedExpression(::google::protobuf::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kExtensionUrisFieldNumber = 1,
    kExtensionsFieldNumber = 2,
    kReferredExprFieldNumber = 3,
    kExpectedTypeUrlsFieldNumber = 6,
    kBaseSchemaFieldNumber = 4,
    kAdvancedExtensionsFieldNumber = 5,
    kVersionFieldNumber = 7,
  };
  // repeated .substrait.extensions.SimpleExtensionURI extension_uris = 1 [json_name = "extensionUris"];
  int extension_uris_size() const;
  private:
  int _internal_extension_uris_size() const;

  public:
  void clear_extension_uris() ;
  ::substrait::extensions::SimpleExtensionURI* mutable_extension_uris(int index);
  ::google::protobuf::RepeatedPtrField< ::substrait::extensions::SimpleExtensionURI >*
      mutable_extension_uris();
  private:
  const ::google::protobuf::RepeatedPtrField<::substrait::extensions::SimpleExtensionURI>& _internal_extension_uris() const;
  ::google::protobuf::RepeatedPtrField<::substrait::extensions::SimpleExtensionURI>* _internal_mutable_extension_uris();
  public:
  const ::substrait::extensions::SimpleExtensionURI& extension_uris(int index) const;
  ::substrait::extensions::SimpleExtensionURI* add_extension_uris();
  const ::google::protobuf::RepeatedPtrField< ::substrait::extensions::SimpleExtensionURI >&
      extension_uris() const;
  // repeated .substrait.extensions.SimpleExtensionDeclaration extensions = 2 [json_name = "extensions"];
  int extensions_size() const;
  private:
  int _internal_extensions_size() const;

  public:
  void clear_extensions() ;
  ::substrait::extensions::SimpleExtensionDeclaration* mutable_extensions(int index);
  ::google::protobuf::RepeatedPtrField< ::substrait::extensions::SimpleExtensionDeclaration >*
      mutable_extensions();
  private:
  const ::google::protobuf::RepeatedPtrField<::substrait::extensions::SimpleExtensionDeclaration>& _internal_extensions() const;
  ::google::protobuf::RepeatedPtrField<::substrait::extensions::SimpleExtensionDeclaration>* _internal_mutable_extensions();
  public:
  const ::substrait::extensions::SimpleExtensionDeclaration& extensions(int index) const;
  ::substrait::extensions::SimpleExtensionDeclaration* add_extensions();
  const ::google::protobuf::RepeatedPtrField< ::substrait::extensions::SimpleExtensionDeclaration >&
      extensions() const;
  // repeated .substrait.ExpressionReference referred_expr = 3 [json_name = "referredExpr"];
  int referred_expr_size() const;
  private:
  int _internal_referred_expr_size() const;

  public:
  void clear_referred_expr() ;
  ::substrait::ExpressionReference* mutable_referred_expr(int index);
  ::google::protobuf::RepeatedPtrField< ::substrait::ExpressionReference >*
      mutable_referred_expr();
  private:
  const ::google::protobuf::RepeatedPtrField<::substrait::ExpressionReference>& _internal_referred_expr() const;
  ::google::protobuf::RepeatedPtrField<::substrait::ExpressionReference>* _internal_mutable_referred_expr();
  public:
  const ::substrait::ExpressionReference& referred_expr(int index) const;
  ::substrait::ExpressionReference* add_referred_expr();
  const ::google::protobuf::RepeatedPtrField< ::substrait::ExpressionReference >&
      referred_expr() const;
  // repeated string expected_type_urls = 6 [json_name = "expectedTypeUrls"];
  int expected_type_urls_size() const;
  private:
  int _internal_expected_type_urls_size() const;

  public:
  void clear_expected_type_urls() ;
  const std::string& expected_type_urls(int index) const;
  std::string* mutable_expected_type_urls(int index);
  void set_expected_type_urls(int index, const std::string& value);
  void set_expected_type_urls(int index, std::string&& value);
  void set_expected_type_urls(int index, const char* value);
  void set_expected_type_urls(int index, const char* value, std::size_t size);
  void set_expected_type_urls(int index, absl::string_view value);
  std::string* add_expected_type_urls();
  void add_expected_type_urls(const std::string& value);
  void add_expected_type_urls(std::string&& value);
  void add_expected_type_urls(const char* value);
  void add_expected_type_urls(const char* value, std::size_t size);
  void add_expected_type_urls(absl::string_view value);
  const ::google::protobuf::RepeatedPtrField<std::string>& expected_type_urls() const;
  ::google::protobuf::RepeatedPtrField<std::string>* mutable_expected_type_urls();

  private:
  const ::google::protobuf::RepeatedPtrField<std::string>& _internal_expected_type_urls() const;
  ::google::protobuf::RepeatedPtrField<std::string>* _internal_mutable_expected_type_urls();

  public:
  // .substrait.NamedStruct base_schema = 4 [json_name = "baseSchema"];
  bool has_base_schema() const;
  void clear_base_schema() ;
  const ::substrait::NamedStruct& base_schema() const;
  PROTOBUF_NODISCARD ::substrait::NamedStruct* release_base_schema();
  ::substrait::NamedStruct* mutable_base_schema();
  void set_allocated_base_schema(::substrait::NamedStruct* value);
  void unsafe_arena_set_allocated_base_schema(::substrait::NamedStruct* value);
  ::substrait::NamedStruct* unsafe_arena_release_base_schema();

  private:
  const ::substrait::NamedStruct& _internal_base_schema() const;
  ::substrait::NamedStruct* _internal_mutable_base_schema();

  public:
  // .substrait.extensions.AdvancedExtension advanced_extensions = 5 [json_name = "advancedExtensions"];
  bool has_advanced_extensions() const;
  void clear_advanced_extensions() ;
  const ::substrait::extensions::AdvancedExtension& advanced_extensions() const;
  PROTOBUF_NODISCARD ::substrait::extensions::AdvancedExtension* release_advanced_extensions();
  ::substrait::extensions::AdvancedExtension* mutable_advanced_extensions();
  void set_allocated_advanced_extensions(::substrait::extensions::AdvancedExtension* value);
  void unsafe_arena_set_allocated_advanced_extensions(::substrait::extensions::AdvancedExtension* value);
  ::substrait::extensions::AdvancedExtension* unsafe_arena_release_advanced_extensions();

  private:
  const ::substrait::extensions::AdvancedExtension& _internal_advanced_extensions() const;
  ::substrait::extensions::AdvancedExtension* _internal_mutable_advanced_extensions();

  public:
  // .substrait.Version version = 7 [json_name = "version"];
  bool has_version() const;
  void clear_version() ;
  const ::substrait::Version& version() const;
  PROTOBUF_NODISCARD ::substrait::Version* release_version();
  ::substrait::Version* mutable_version();
  void set_allocated_version(::substrait::Version* value);
  void unsafe_arena_set_allocated_version(::substrait::Version* value);
  ::substrait::Version* unsafe_arena_release_version();

  private:
  const ::substrait::Version& _internal_version() const;
  ::substrait::Version* _internal_mutable_version();

  public:
  // @@protoc_insertion_point(class_scope:substrait.ExtendedExpression)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 7, 6, 55, 2> _table_;
  template <typename T> friend class ::google::protobuf::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::substrait::extensions::SimpleExtensionURI > extension_uris_;
    ::google::protobuf::RepeatedPtrField< ::substrait::extensions::SimpleExtensionDeclaration > extensions_;
    ::google::protobuf::RepeatedPtrField< ::substrait::ExpressionReference > referred_expr_;
    ::google::protobuf::RepeatedPtrField<std::string> expected_type_urls_;
    ::substrait::NamedStruct* base_schema_;
    ::substrait::extensions::AdvancedExtension* advanced_extensions_;
    ::substrait::Version* version_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_substrait_2fextended_5fexpression_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// ExpressionReference

// .substrait.Expression expression = 1 [json_name = "expression"];
inline bool ExpressionReference::has_expression() const {
  return expr_type_case() == kExpression;
}
inline bool ExpressionReference::_internal_has_expression() const {
  return expr_type_case() == kExpression;
}
inline void ExpressionReference::set_has_expression() {
  _impl_._oneof_case_[0] = kExpression;
}
inline ::substrait::Expression* ExpressionReference::release_expression() {
  // @@protoc_insertion_point(field_release:substrait.ExpressionReference.expression)
  if (expr_type_case() == kExpression) {
    clear_has_expr_type();
    ::substrait::Expression* temp = _impl_.expr_type_.expression_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.expr_type_.expression_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::substrait::Expression& ExpressionReference::_internal_expression() const {
  return expr_type_case() == kExpression
      ? *_impl_.expr_type_.expression_
      : reinterpret_cast<::substrait::Expression&>(::substrait::_Expression_default_instance_);
}
inline const ::substrait::Expression& ExpressionReference::expression() const {
  // @@protoc_insertion_point(field_get:substrait.ExpressionReference.expression)
  return _internal_expression();
}
inline ::substrait::Expression* ExpressionReference::unsafe_arena_release_expression() {
  // @@protoc_insertion_point(field_unsafe_arena_release:substrait.ExpressionReference.expression)
  if (expr_type_case() == kExpression) {
    clear_has_expr_type();
    ::substrait::Expression* temp = _impl_.expr_type_.expression_;
    _impl_.expr_type_.expression_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void ExpressionReference::unsafe_arena_set_allocated_expression(::substrait::Expression* expression) {
  clear_expr_type();
  if (expression) {
    set_has_expression();
    _impl_.expr_type_.expression_ = expression;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:substrait.ExpressionReference.expression)
}
inline ::substrait::Expression* ExpressionReference::_internal_mutable_expression() {
  if (expr_type_case() != kExpression) {
    clear_expr_type();
    set_has_expression();
    _impl_.expr_type_.expression_ = CreateMaybeMessage< ::substrait::Expression >(GetArenaForAllocation());
  }
  return _impl_.expr_type_.expression_;
}
inline ::substrait::Expression* ExpressionReference::mutable_expression() {
  ::substrait::Expression* _msg = _internal_mutable_expression();
  // @@protoc_insertion_point(field_mutable:substrait.ExpressionReference.expression)
  return _msg;
}

// .substrait.AggregateFunction measure = 2 [json_name = "measure"];
inline bool ExpressionReference::has_measure() const {
  return expr_type_case() == kMeasure;
}
inline bool ExpressionReference::_internal_has_measure() const {
  return expr_type_case() == kMeasure;
}
inline void ExpressionReference::set_has_measure() {
  _impl_._oneof_case_[0] = kMeasure;
}
inline ::substrait::AggregateFunction* ExpressionReference::release_measure() {
  // @@protoc_insertion_point(field_release:substrait.ExpressionReference.measure)
  if (expr_type_case() == kMeasure) {
    clear_has_expr_type();
    ::substrait::AggregateFunction* temp = _impl_.expr_type_.measure_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.expr_type_.measure_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::substrait::AggregateFunction& ExpressionReference::_internal_measure() const {
  return expr_type_case() == kMeasure
      ? *_impl_.expr_type_.measure_
      : reinterpret_cast<::substrait::AggregateFunction&>(::substrait::_AggregateFunction_default_instance_);
}
inline const ::substrait::AggregateFunction& ExpressionReference::measure() const {
  // @@protoc_insertion_point(field_get:substrait.ExpressionReference.measure)
  return _internal_measure();
}
inline ::substrait::AggregateFunction* ExpressionReference::unsafe_arena_release_measure() {
  // @@protoc_insertion_point(field_unsafe_arena_release:substrait.ExpressionReference.measure)
  if (expr_type_case() == kMeasure) {
    clear_has_expr_type();
    ::substrait::AggregateFunction* temp = _impl_.expr_type_.measure_;
    _impl_.expr_type_.measure_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void ExpressionReference::unsafe_arena_set_allocated_measure(::substrait::AggregateFunction* measure) {
  clear_expr_type();
  if (measure) {
    set_has_measure();
    _impl_.expr_type_.measure_ = measure;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:substrait.ExpressionReference.measure)
}
inline ::substrait::AggregateFunction* ExpressionReference::_internal_mutable_measure() {
  if (expr_type_case() != kMeasure) {
    clear_expr_type();
    set_has_measure();
    _impl_.expr_type_.measure_ = CreateMaybeMessage< ::substrait::AggregateFunction >(GetArenaForAllocation());
  }
  return _impl_.expr_type_.measure_;
}
inline ::substrait::AggregateFunction* ExpressionReference::mutable_measure() {
  ::substrait::AggregateFunction* _msg = _internal_mutable_measure();
  // @@protoc_insertion_point(field_mutable:substrait.ExpressionReference.measure)
  return _msg;
}

// repeated string output_names = 3 [json_name = "outputNames"];
inline int ExpressionReference::_internal_output_names_size() const {
  return _internal_output_names().size();
}
inline int ExpressionReference::output_names_size() const {
  return _internal_output_names_size();
}
inline void ExpressionReference::clear_output_names() {
  _internal_mutable_output_names()->Clear();
}
inline std::string* ExpressionReference::add_output_names() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  std::string* _s = _internal_mutable_output_names()->Add();
  // @@protoc_insertion_point(field_add_mutable:substrait.ExpressionReference.output_names)
  return _s;
}
inline const std::string& ExpressionReference::output_names(int index) const {
  // @@protoc_insertion_point(field_get:substrait.ExpressionReference.output_names)
  return _internal_output_names().Get(index);
}
inline std::string* ExpressionReference::mutable_output_names(int index) {
  // @@protoc_insertion_point(field_mutable:substrait.ExpressionReference.output_names)
  return _internal_mutable_output_names()->Mutable(index);
}
inline void ExpressionReference::set_output_names(int index, const std::string& value) {
  _internal_mutable_output_names()->Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:substrait.ExpressionReference.output_names)
}
inline void ExpressionReference::set_output_names(int index, std::string&& value) {
  _internal_mutable_output_names()->Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:substrait.ExpressionReference.output_names)
}
inline void ExpressionReference::set_output_names(int index, const char* value) {
  ABSL_DCHECK(value != nullptr);
  _internal_mutable_output_names()->Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:substrait.ExpressionReference.output_names)
}
inline void ExpressionReference::set_output_names(int index, const char* value,
                              std::size_t size) {
  _internal_mutable_output_names()->Mutable(index)->assign(
      reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:substrait.ExpressionReference.output_names)
}
inline void ExpressionReference::set_output_names(int index, absl::string_view value) {
  _internal_mutable_output_names()->Mutable(index)->assign(value.data(),
                                                     value.size());
  // @@protoc_insertion_point(field_set_string_piece:substrait.ExpressionReference.output_names)
}
inline void ExpressionReference::add_output_names(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _internal_mutable_output_names()->Add()->assign(value);
  // @@protoc_insertion_point(field_add:substrait.ExpressionReference.output_names)
}
inline void ExpressionReference::add_output_names(std::string&& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _internal_mutable_output_names()->Add(std::move(value));
  // @@protoc_insertion_point(field_add:substrait.ExpressionReference.output_names)
}
inline void ExpressionReference::add_output_names(const char* value) {
  ABSL_DCHECK(value != nullptr);
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _internal_mutable_output_names()->Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:substrait.ExpressionReference.output_names)
}
inline void ExpressionReference::add_output_names(const char* value, std::size_t size) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _internal_mutable_output_names()->Add()->assign(
      reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:substrait.ExpressionReference.output_names)
}
inline void ExpressionReference::add_output_names(absl::string_view value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _internal_mutable_output_names()->Add()->assign(value.data(), value.size());
  // @@protoc_insertion_point(field_add_string_piece:substrait.ExpressionReference.output_names)
}
inline const ::google::protobuf::RepeatedPtrField<std::string>&
ExpressionReference::output_names() const {
  // @@protoc_insertion_point(field_list:substrait.ExpressionReference.output_names)
  return _internal_output_names();
}
inline ::google::protobuf::RepeatedPtrField<std::string>* ExpressionReference::mutable_output_names() {
  // @@protoc_insertion_point(field_mutable_list:substrait.ExpressionReference.output_names)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _internal_mutable_output_names();
}
inline const ::google::protobuf::RepeatedPtrField<std::string>&
ExpressionReference::_internal_output_names() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.output_names_;
}
inline ::google::protobuf::RepeatedPtrField<std::string>*
ExpressionReference::_internal_mutable_output_names() {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return &_impl_.output_names_;
}

inline bool ExpressionReference::has_expr_type() const {
  return expr_type_case() != EXPR_TYPE_NOT_SET;
}
inline void ExpressionReference::clear_has_expr_type() {
  _impl_._oneof_case_[0] = EXPR_TYPE_NOT_SET;
}
inline ExpressionReference::ExprTypeCase ExpressionReference::expr_type_case() const {
  return ExpressionReference::ExprTypeCase(_impl_._oneof_case_[0]);
}
// -------------------------------------------------------------------

// ExtendedExpression

// .substrait.Version version = 7 [json_name = "version"];
inline bool ExtendedExpression::has_version() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.version_ != nullptr);
  return value;
}
inline const ::substrait::Version& ExtendedExpression::_internal_version() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  const ::substrait::Version* p = _impl_.version_;
  return p != nullptr ? *p : reinterpret_cast<const ::substrait::Version&>(::substrait::_Version_default_instance_);
}
inline const ::substrait::Version& ExtendedExpression::version() const {
  // @@protoc_insertion_point(field_get:substrait.ExtendedExpression.version)
  return _internal_version();
}
inline void ExtendedExpression::unsafe_arena_set_allocated_version(::substrait::Version* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.version_);
  }
  _impl_.version_ = reinterpret_cast<::substrait::Version*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:substrait.ExtendedExpression.version)
}
inline ::substrait::Version* ExtendedExpression::release_version() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);

  _impl_._has_bits_[0] &= ~0x00000004u;
  ::substrait::Version* released = _impl_.version_;
  _impl_.version_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArenaForAllocation() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::substrait::Version* ExtendedExpression::unsafe_arena_release_version() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:substrait.ExtendedExpression.version)

  _impl_._has_bits_[0] &= ~0x00000004u;
  ::substrait::Version* temp = _impl_.version_;
  _impl_.version_ = nullptr;
  return temp;
}
inline ::substrait::Version* ExtendedExpression::_internal_mutable_version() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000004u;
  if (_impl_.version_ == nullptr) {
    auto* p = CreateMaybeMessage<::substrait::Version>(GetArenaForAllocation());
    _impl_.version_ = reinterpret_cast<::substrait::Version*>(p);
  }
  return _impl_.version_;
}
inline ::substrait::Version* ExtendedExpression::mutable_version() {
  ::substrait::Version* _msg = _internal_mutable_version();
  // @@protoc_insertion_point(field_mutable:substrait.ExtendedExpression.version)
  return _msg;
}
inline void ExtendedExpression::set_allocated_version(::substrait::Version* value) {
  ::google::protobuf::Arena* message_arena = GetArenaForAllocation();
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.version_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena =
        ::google::protobuf::Arena::InternalGetOwningArena(reinterpret_cast<::google::protobuf::MessageLite*>(value));
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }

  _impl_.version_ = reinterpret_cast<::substrait::Version*>(value);
  // @@protoc_insertion_point(field_set_allocated:substrait.ExtendedExpression.version)
}

// repeated .substrait.extensions.SimpleExtensionURI extension_uris = 1 [json_name = "extensionUris"];
inline int ExtendedExpression::_internal_extension_uris_size() const {
  return _internal_extension_uris().size();
}
inline int ExtendedExpression::extension_uris_size() const {
  return _internal_extension_uris_size();
}
inline ::substrait::extensions::SimpleExtensionURI* ExtendedExpression::mutable_extension_uris(int index) {
  // @@protoc_insertion_point(field_mutable:substrait.ExtendedExpression.extension_uris)
  return _internal_mutable_extension_uris()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::substrait::extensions::SimpleExtensionURI >*
ExtendedExpression::mutable_extension_uris() {
  // @@protoc_insertion_point(field_mutable_list:substrait.ExtendedExpression.extension_uris)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _internal_mutable_extension_uris();
}
inline const ::substrait::extensions::SimpleExtensionURI& ExtendedExpression::extension_uris(int index) const {
  // @@protoc_insertion_point(field_get:substrait.ExtendedExpression.extension_uris)
    return _internal_extension_uris().Get(index);
}
inline ::substrait::extensions::SimpleExtensionURI* ExtendedExpression::add_extension_uris() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::substrait::extensions::SimpleExtensionURI* _add = _internal_mutable_extension_uris()->Add();
  // @@protoc_insertion_point(field_add:substrait.ExtendedExpression.extension_uris)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField< ::substrait::extensions::SimpleExtensionURI >&
ExtendedExpression::extension_uris() const {
  // @@protoc_insertion_point(field_list:substrait.ExtendedExpression.extension_uris)
  return _internal_extension_uris();
}
inline const ::google::protobuf::RepeatedPtrField<::substrait::extensions::SimpleExtensionURI>&
ExtendedExpression::_internal_extension_uris() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.extension_uris_;
}
inline ::google::protobuf::RepeatedPtrField<::substrait::extensions::SimpleExtensionURI>*
ExtendedExpression::_internal_mutable_extension_uris() {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return &_impl_.extension_uris_;
}

// repeated .substrait.extensions.SimpleExtensionDeclaration extensions = 2 [json_name = "extensions"];
inline int ExtendedExpression::_internal_extensions_size() const {
  return _internal_extensions().size();
}
inline int ExtendedExpression::extensions_size() const {
  return _internal_extensions_size();
}
inline ::substrait::extensions::SimpleExtensionDeclaration* ExtendedExpression::mutable_extensions(int index) {
  // @@protoc_insertion_point(field_mutable:substrait.ExtendedExpression.extensions)
  return _internal_mutable_extensions()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::substrait::extensions::SimpleExtensionDeclaration >*
ExtendedExpression::mutable_extensions() {
  // @@protoc_insertion_point(field_mutable_list:substrait.ExtendedExpression.extensions)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _internal_mutable_extensions();
}
inline const ::substrait::extensions::SimpleExtensionDeclaration& ExtendedExpression::extensions(int index) const {
  // @@protoc_insertion_point(field_get:substrait.ExtendedExpression.extensions)
    return _internal_extensions().Get(index);
}
inline ::substrait::extensions::SimpleExtensionDeclaration* ExtendedExpression::add_extensions() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::substrait::extensions::SimpleExtensionDeclaration* _add = _internal_mutable_extensions()->Add();
  // @@protoc_insertion_point(field_add:substrait.ExtendedExpression.extensions)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField< ::substrait::extensions::SimpleExtensionDeclaration >&
ExtendedExpression::extensions() const {
  // @@protoc_insertion_point(field_list:substrait.ExtendedExpression.extensions)
  return _internal_extensions();
}
inline const ::google::protobuf::RepeatedPtrField<::substrait::extensions::SimpleExtensionDeclaration>&
ExtendedExpression::_internal_extensions() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.extensions_;
}
inline ::google::protobuf::RepeatedPtrField<::substrait::extensions::SimpleExtensionDeclaration>*
ExtendedExpression::_internal_mutable_extensions() {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return &_impl_.extensions_;
}

// repeated .substrait.ExpressionReference referred_expr = 3 [json_name = "referredExpr"];
inline int ExtendedExpression::_internal_referred_expr_size() const {
  return _internal_referred_expr().size();
}
inline int ExtendedExpression::referred_expr_size() const {
  return _internal_referred_expr_size();
}
inline void ExtendedExpression::clear_referred_expr() {
  _internal_mutable_referred_expr()->Clear();
}
inline ::substrait::ExpressionReference* ExtendedExpression::mutable_referred_expr(int index) {
  // @@protoc_insertion_point(field_mutable:substrait.ExtendedExpression.referred_expr)
  return _internal_mutable_referred_expr()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::substrait::ExpressionReference >*
ExtendedExpression::mutable_referred_expr() {
  // @@protoc_insertion_point(field_mutable_list:substrait.ExtendedExpression.referred_expr)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _internal_mutable_referred_expr();
}
inline const ::substrait::ExpressionReference& ExtendedExpression::referred_expr(int index) const {
  // @@protoc_insertion_point(field_get:substrait.ExtendedExpression.referred_expr)
    return _internal_referred_expr().Get(index);
}
inline ::substrait::ExpressionReference* ExtendedExpression::add_referred_expr() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::substrait::ExpressionReference* _add = _internal_mutable_referred_expr()->Add();
  // @@protoc_insertion_point(field_add:substrait.ExtendedExpression.referred_expr)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField< ::substrait::ExpressionReference >&
ExtendedExpression::referred_expr() const {
  // @@protoc_insertion_point(field_list:substrait.ExtendedExpression.referred_expr)
  return _internal_referred_expr();
}
inline const ::google::protobuf::RepeatedPtrField<::substrait::ExpressionReference>&
ExtendedExpression::_internal_referred_expr() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.referred_expr_;
}
inline ::google::protobuf::RepeatedPtrField<::substrait::ExpressionReference>*
ExtendedExpression::_internal_mutable_referred_expr() {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return &_impl_.referred_expr_;
}

// .substrait.NamedStruct base_schema = 4 [json_name = "baseSchema"];
inline bool ExtendedExpression::has_base_schema() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.base_schema_ != nullptr);
  return value;
}
inline const ::substrait::NamedStruct& ExtendedExpression::_internal_base_schema() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  const ::substrait::NamedStruct* p = _impl_.base_schema_;
  return p != nullptr ? *p : reinterpret_cast<const ::substrait::NamedStruct&>(::substrait::_NamedStruct_default_instance_);
}
inline const ::substrait::NamedStruct& ExtendedExpression::base_schema() const {
  // @@protoc_insertion_point(field_get:substrait.ExtendedExpression.base_schema)
  return _internal_base_schema();
}
inline void ExtendedExpression::unsafe_arena_set_allocated_base_schema(::substrait::NamedStruct* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.base_schema_);
  }
  _impl_.base_schema_ = reinterpret_cast<::substrait::NamedStruct*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:substrait.ExtendedExpression.base_schema)
}
inline ::substrait::NamedStruct* ExtendedExpression::release_base_schema() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::substrait::NamedStruct* released = _impl_.base_schema_;
  _impl_.base_schema_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArenaForAllocation() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::substrait::NamedStruct* ExtendedExpression::unsafe_arena_release_base_schema() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:substrait.ExtendedExpression.base_schema)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::substrait::NamedStruct* temp = _impl_.base_schema_;
  _impl_.base_schema_ = nullptr;
  return temp;
}
inline ::substrait::NamedStruct* ExtendedExpression::_internal_mutable_base_schema() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  if (_impl_.base_schema_ == nullptr) {
    auto* p = CreateMaybeMessage<::substrait::NamedStruct>(GetArenaForAllocation());
    _impl_.base_schema_ = reinterpret_cast<::substrait::NamedStruct*>(p);
  }
  return _impl_.base_schema_;
}
inline ::substrait::NamedStruct* ExtendedExpression::mutable_base_schema() {
  ::substrait::NamedStruct* _msg = _internal_mutable_base_schema();
  // @@protoc_insertion_point(field_mutable:substrait.ExtendedExpression.base_schema)
  return _msg;
}
inline void ExtendedExpression::set_allocated_base_schema(::substrait::NamedStruct* value) {
  ::google::protobuf::Arena* message_arena = GetArenaForAllocation();
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.base_schema_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena =
        ::google::protobuf::Arena::InternalGetOwningArena(reinterpret_cast<::google::protobuf::MessageLite*>(value));
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.base_schema_ = reinterpret_cast<::substrait::NamedStruct*>(value);
  // @@protoc_insertion_point(field_set_allocated:substrait.ExtendedExpression.base_schema)
}

// .substrait.extensions.AdvancedExtension advanced_extensions = 5 [json_name = "advancedExtensions"];
inline bool ExtendedExpression::has_advanced_extensions() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.advanced_extensions_ != nullptr);
  return value;
}
inline const ::substrait::extensions::AdvancedExtension& ExtendedExpression::_internal_advanced_extensions() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  const ::substrait::extensions::AdvancedExtension* p = _impl_.advanced_extensions_;
  return p != nullptr ? *p : reinterpret_cast<const ::substrait::extensions::AdvancedExtension&>(::substrait::extensions::_AdvancedExtension_default_instance_);
}
inline const ::substrait::extensions::AdvancedExtension& ExtendedExpression::advanced_extensions() const {
  // @@protoc_insertion_point(field_get:substrait.ExtendedExpression.advanced_extensions)
  return _internal_advanced_extensions();
}
inline void ExtendedExpression::unsafe_arena_set_allocated_advanced_extensions(::substrait::extensions::AdvancedExtension* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.advanced_extensions_);
  }
  _impl_.advanced_extensions_ = reinterpret_cast<::substrait::extensions::AdvancedExtension*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:substrait.ExtendedExpression.advanced_extensions)
}
inline ::substrait::extensions::AdvancedExtension* ExtendedExpression::release_advanced_extensions() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::substrait::extensions::AdvancedExtension* released = _impl_.advanced_extensions_;
  _impl_.advanced_extensions_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArenaForAllocation() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::substrait::extensions::AdvancedExtension* ExtendedExpression::unsafe_arena_release_advanced_extensions() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:substrait.ExtendedExpression.advanced_extensions)

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::substrait::extensions::AdvancedExtension* temp = _impl_.advanced_extensions_;
  _impl_.advanced_extensions_ = nullptr;
  return temp;
}
inline ::substrait::extensions::AdvancedExtension* ExtendedExpression::_internal_mutable_advanced_extensions() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000002u;
  if (_impl_.advanced_extensions_ == nullptr) {
    auto* p = CreateMaybeMessage<::substrait::extensions::AdvancedExtension>(GetArenaForAllocation());
    _impl_.advanced_extensions_ = reinterpret_cast<::substrait::extensions::AdvancedExtension*>(p);
  }
  return _impl_.advanced_extensions_;
}
inline ::substrait::extensions::AdvancedExtension* ExtendedExpression::mutable_advanced_extensions() {
  ::substrait::extensions::AdvancedExtension* _msg = _internal_mutable_advanced_extensions();
  // @@protoc_insertion_point(field_mutable:substrait.ExtendedExpression.advanced_extensions)
  return _msg;
}
inline void ExtendedExpression::set_allocated_advanced_extensions(::substrait::extensions::AdvancedExtension* value) {
  ::google::protobuf::Arena* message_arena = GetArenaForAllocation();
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.advanced_extensions_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena =
        ::google::protobuf::Arena::InternalGetOwningArena(reinterpret_cast<::google::protobuf::MessageLite*>(value));
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }

  _impl_.advanced_extensions_ = reinterpret_cast<::substrait::extensions::AdvancedExtension*>(value);
  // @@protoc_insertion_point(field_set_allocated:substrait.ExtendedExpression.advanced_extensions)
}

// repeated string expected_type_urls = 6 [json_name = "expectedTypeUrls"];
inline int ExtendedExpression::_internal_expected_type_urls_size() const {
  return _internal_expected_type_urls().size();
}
inline int ExtendedExpression::expected_type_urls_size() const {
  return _internal_expected_type_urls_size();
}
inline void ExtendedExpression::clear_expected_type_urls() {
  _internal_mutable_expected_type_urls()->Clear();
}
inline std::string* ExtendedExpression::add_expected_type_urls() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  std::string* _s = _internal_mutable_expected_type_urls()->Add();
  // @@protoc_insertion_point(field_add_mutable:substrait.ExtendedExpression.expected_type_urls)
  return _s;
}
inline const std::string& ExtendedExpression::expected_type_urls(int index) const {
  // @@protoc_insertion_point(field_get:substrait.ExtendedExpression.expected_type_urls)
  return _internal_expected_type_urls().Get(index);
}
inline std::string* ExtendedExpression::mutable_expected_type_urls(int index) {
  // @@protoc_insertion_point(field_mutable:substrait.ExtendedExpression.expected_type_urls)
  return _internal_mutable_expected_type_urls()->Mutable(index);
}
inline void ExtendedExpression::set_expected_type_urls(int index, const std::string& value) {
  _internal_mutable_expected_type_urls()->Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:substrait.ExtendedExpression.expected_type_urls)
}
inline void ExtendedExpression::set_expected_type_urls(int index, std::string&& value) {
  _internal_mutable_expected_type_urls()->Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:substrait.ExtendedExpression.expected_type_urls)
}
inline void ExtendedExpression::set_expected_type_urls(int index, const char* value) {
  ABSL_DCHECK(value != nullptr);
  _internal_mutable_expected_type_urls()->Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:substrait.ExtendedExpression.expected_type_urls)
}
inline void ExtendedExpression::set_expected_type_urls(int index, const char* value,
                              std::size_t size) {
  _internal_mutable_expected_type_urls()->Mutable(index)->assign(
      reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:substrait.ExtendedExpression.expected_type_urls)
}
inline void ExtendedExpression::set_expected_type_urls(int index, absl::string_view value) {
  _internal_mutable_expected_type_urls()->Mutable(index)->assign(value.data(),
                                                     value.size());
  // @@protoc_insertion_point(field_set_string_piece:substrait.ExtendedExpression.expected_type_urls)
}
inline void ExtendedExpression::add_expected_type_urls(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _internal_mutable_expected_type_urls()->Add()->assign(value);
  // @@protoc_insertion_point(field_add:substrait.ExtendedExpression.expected_type_urls)
}
inline void ExtendedExpression::add_expected_type_urls(std::string&& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _internal_mutable_expected_type_urls()->Add(std::move(value));
  // @@protoc_insertion_point(field_add:substrait.ExtendedExpression.expected_type_urls)
}
inline void ExtendedExpression::add_expected_type_urls(const char* value) {
  ABSL_DCHECK(value != nullptr);
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _internal_mutable_expected_type_urls()->Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:substrait.ExtendedExpression.expected_type_urls)
}
inline void ExtendedExpression::add_expected_type_urls(const char* value, std::size_t size) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _internal_mutable_expected_type_urls()->Add()->assign(
      reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:substrait.ExtendedExpression.expected_type_urls)
}
inline void ExtendedExpression::add_expected_type_urls(absl::string_view value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _internal_mutable_expected_type_urls()->Add()->assign(value.data(), value.size());
  // @@protoc_insertion_point(field_add_string_piece:substrait.ExtendedExpression.expected_type_urls)
}
inline const ::google::protobuf::RepeatedPtrField<std::string>&
ExtendedExpression::expected_type_urls() const {
  // @@protoc_insertion_point(field_list:substrait.ExtendedExpression.expected_type_urls)
  return _internal_expected_type_urls();
}
inline ::google::protobuf::RepeatedPtrField<std::string>* ExtendedExpression::mutable_expected_type_urls() {
  // @@protoc_insertion_point(field_mutable_list:substrait.ExtendedExpression.expected_type_urls)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _internal_mutable_expected_type_urls();
}
inline const ::google::protobuf::RepeatedPtrField<std::string>&
ExtendedExpression::_internal_expected_type_urls() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.expected_type_urls_;
}
inline ::google::protobuf::RepeatedPtrField<std::string>*
ExtendedExpression::_internal_mutable_expected_type_urls() {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return &_impl_.expected_type_urls_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace substrait


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_substrait_2fextended_5fexpression_2eproto_2epb_2eh
