# ------------------------------
# Headers and Sources

# >> Headers
libskytether_headers += files(
   'apidep_duckdb.hpp'
  ,'adapter_duckdb.hpp'
  ,'custom_extensions.hpp'
)


# >> Sources
libskytether_sources += files(
   'engine_duckdb.cpp'
  ,'translate_operators.cpp'
  ,'translate_expressions.cpp'
  ,'translate_types.cpp'
  ,'custom_extensions.cpp'
  ,'custom_extensions_generated.cpp'
)

