# ------------------------------
# Headers and Sources

# >> Headers
libskytether_headers += files(
   'apidep_flight.hpp'
  ,'types.hpp'
  ,'service_skytether.hpp'
  ,'service_topology.hpp'
  ,'service_duckdb.hpp'
  ,'client_skytether.hpp'
)

# >> Sources
libskytether_sources += files(
   'adapter_flight.cpp'
  ,'service_skytether.cpp'
  ,'service_topology.cpp'
  ,'service_duckdb.cpp'
  ,'client_skytether.cpp'
)

